name: Terraform Format & Validate

# Run this workflow on every push or pull request to main branch
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-validate-fmt.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-checks:
    name: Terraform Format & Validate
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::887724315744:role/github-actions-oidc-role-dev
          aws-region: eu-central-1 
          
      - name: Export Snowflake private key
        run: |
          echo "TF_VAR_snowflake_private_key=${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" >> $GITHUB_ENV


     # Step 3 
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./infra

      # Step 4: Run 'terraform fmt' to check formatting
      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

 

      # Step 5: Run 'terraform validate' to check configuration syntax
      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: ./infra


