name: Terraform Apply after PR Merge

# Trigger only after code is merged to main
on:
  push:
    branches:
      - main
      #- test-oidc-connection
    paths:
      - 'infra/**'
      - 'modules/glue/**'
      - 'modules/iam/**'
      - 'modules/s3_ingestion/**'
      - 'modules/sns/**'
      #- 'modules/lambda/**'
      #- 'modules/stepfunction/**'
      #- 'modules/snowflake/**'
      #- 'modules/snowflake-integration/**'
      - '.github/workflows/terraform-post-merge-apply.yaml'

# Permissions required for GitHub Actions to assume the OIDC role
permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply with Manual Approval
    runs-on: ubuntu-latest

    # Protect this job behind environment approval
    #environment: dev-approve     # this enables manual approval before terraform apply

    steps:
      # Step 1: Checkout repository code
      - name: Checkout source code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC role
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::887724315744:role/github-actions-oidc-role-dev
          aws-region: eu-central-1

      - name: Test AWS Identity 
        run: aws sts get-caller-identity

      # Step 3: Install Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Step 4: Initialize Terraform in the infra directory
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      # Step 5: Run Terraform Plan to preview changes
      - name: Terraform Plan (Infra)
        run: terraform plan -input=false
        working-directory: ./infra

      # Step 6: Terraform Apply (run only after manual approval)
      - name: Terraform Apply (after approval)
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra



